version: "3.9"
services:
  db:
    image: postgres:16-alpine
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: vercel_notes
      POSTGRES_USER: vercel
      POSTGRES_PASSWORD: vercel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vercel -d vercel_notes"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
